[build-system]
requires = ["setuptools", "wheel", "pybind11", "cython"]
build-backend = "setuptools.build_meta"

[project]
name = "quantumcrypt"
version = "0.1.0"
description = "A post-quantum encryption library"
authors = [{name = "Izumi", email = "izumi@cyberverse.net"}]
